services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: spotter
    env_file: .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SPOTTER_SA_PASSWORD}
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
